import type { Metadata } from "next"

import "@/app/globals.css"
import '@/css/styles.css'

import { UserProvider } from "@/context/UserContext"
import Content from "@/components/content"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <UserProvider>
      <html lang="en">
        <body
          className={`h-[100dvh] antialiased overflow-x-hidden`}
        >
          <Content>{children}</Content>
        </body>
      </html>
    </UserProvider>
  )
}