import type { Metadata } from "next"

import "@/app/globals.css"
import '@/css/styles.css'

import ClientLayout from "@/components/ClientLayout"
import { UserProvider } from "@/context/UserContext"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <UserProvider>
      <html lang="en">
        <body
          className={`min-h-[100vh] antialiased overflow-x-hidden`}
        >
          <ClientLayout>{children}</ClientLayout>
        </body>
      </html>
    </UserProvider>
  )
}