import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "../css/styles.css";
import { ThemeProvider } from "@/src/components/ThemeProvider";
import { Toaster } from "sonner";
import ClientWrapper from "@/components/ui/ClientWrapper"; // Import the client component

import "@/app/globals.css"
import '@/css/styles.css'

import { UserProvider } from "@/context/UserContext"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light" style={{ colorScheme: "light" }}>
      <body>
        <UserProvider>
          <ThemeProvider
            defaultTheme="system"
            attribute="class"
            enableSystem={true}
            disableTransitionOnChange={true}
          >
            <Toaster richColors position="top-center" />
            <ClientWrapper>{children}</ClientWrapper> {/* Use the client component */}
          </ThemeProvider>
        </UserProvider>
      </body>
    </html>
  );
}