// layout.tsx
import type { Metadata } from "next";
import { ThemeProvider } from "../components/ThemeProvider";
import { Toaster } from "sonner";
import ClientWrapper from "@/components/ui/ClientWrapper";

import "@/app/globals.css"
import '@/css/styles.css'

import { UserProvider } from "@/context/UserContext"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // REMOVE 'className="light"' and 'style={{ colorScheme: "light" }}'
    // ADD 'suppressHydrationWarning' to prevent React from complaining during initial render
    <html lang="en" suppressHydrationWarning>
      <body>
        <UserProvider>
          <ThemeProvider
            defaultTheme="system"
            attribute="class" // This tells the ThemeProvider to toggle 'dark'/'light' classes on the html tag
            enableSystem={true}
            disableTransitionOnChange={true}
          >
            <Toaster richColors position="top-center" />
            <ClientWrapper>{children}</ClientWrapper>
          </ThemeProvider>
        </UserProvider>
      </body>
    </html>
  );
}