import type { Metadata } from "next"

import "@/app/globals.css"
import '@/css/styles.css'

import Content from "@/components/content"
import Footer from "@/components/Footer"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`min-h-[100dvh] antialiased overflow-x-hidden`}
      >
        <Content>{children}</Content>
        <Footer />
      </body>
    </html>
  )
}